# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo

    steps:
      - npm install
      - npm install newman
      - node_modules/.bin/newman run postman/ffc-api-requirement-path.postman_collection.json -e postman/ffc-api-test.postman_environment.json
